### ISSUE TITLE
오류 메시지를 전달 받았을 때 표기될 화면 구현 요청

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-client#31]
- status 500대, 400대 로 response 될 때 표기될 화면을 요청드립니다.
- response 되는 오류 코드에 대해서는 API Docs 내 `오류 코드` 에 정리해두었습니다.

**Comment by YeseopLee** [comment]
에러 핸들링에 대한 로직은 완성하였고,
400대 에러 T_004 에러에 대하여 토큰이 유효하지 않을 시, 토큰 재발급 후 데이터를 다시 불러오게끔 처리하였습니다. 
외의 에러에 대해서는 관련 기능들이 구현 될 때 ( ex) 게시물 상세조회 에러 ) 계속해서 추가하겠습니다.

**Comment by YeseopLee** [comment]
현재 (2022.05.01) 발견된 부분에 대해서는 해당 이슈 대응 완료하였습니다.
추후 새롭게 발견되는 경우에는 해당 상황에 대하여 새로 이슈를 남겨주면 확인 후 대응하겠습니다.
