### ISSUE TITLE
다크모드 대응 요청

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-client#67]
![KakaoTalk_Image_2022-02-10-07-29-02](https://user-images.githubusercontent.com/15000594/153301104-5260dae1-3b0e-4117-9a18-12ec02d3b50d.jpeg)

다크모드인 경우에 위와 같이 
배경, 상단 아이콘, 하단 아이콘이 잘 안보이는 상태로 확인됩니다.

우선순위는 낮게 주셔도 괜찮기 때문에 핵심 기능 구현 후 확인해주셔도 괜찮습니다. 부탁드리겠습니다.

**Comment by YeseopLee** [comment]
@leehandsub 작업 완료하였으므로 close 하겠습니다.
