### ISSUE TITLE
채팅방 보완 요청드립니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-client#99]
![Screenshot_20220313-123948_bookwhale](https://user-images.githubusercontent.com/15000594/158044111-4c26a07c-3a32-452e-8e3f-4e0bd93801f3.png)

1. 다크모드 대응 요청 드립니다. 다크모드인 경우 상단과 같이 나오게 되네요.
    1. 채팅 입력 내용이 보이지 않습니다. ("안녕하" 입력 상태)
    2. 채팅 메시지가 보이지 않습니다. ("안녕하세요" 로 입력한 후 메시지 출력된 상태)
2. 채팅방 상단에 판매글을 제목으로 보여줄 수 있을까요? 어떤 채팅방에 접속중인지 구분이 용이할 것 같이 의견남깁니다.

**Comment by YeseopLee** [comment]
해당사항 대응 완료하였습니다.

#102
